Improved implementation to kill a job
slub/ocrd_monitor pull request #37
Opened 2023-08-17 14:17 UTC by markusweigelt

The previous implementation was not sufficient for killing jobs.

The invocation using the host `ocrd-manager`did not work, because the browser sends requests from the host, and here `localhost` was the correct host.

However, this leads to a CORS problem in the browser.

Therefore, the monitor was extended with the URL `/jobs/kill/%PID%` and sends an HTTP request to the manager. From the monitor's perspective, the manager can be found under the host `ocrd-manager`.

The URL to the manager's endpoint is passed to the monitor as an environment variable when it starts.

2023-08-17 15:17 UTC, SvenMarcus requested changes

2023-08-17 15:17 UTC, SvenMarcus commented on ocrdmonitor/server/jobs.py
> +            print(f"Error response {exc.response.status_code} while requesting {exc.request.url!r}.")
It would be better to user the logging module instead of print.

2023-08-17 16:03 UTC, bertsky commented
> The invocation using the host `ocrd-manager`did not work, because the browser sends requests from the host, and here `localhost` was the correct host.
> 
> However, this leads to a CORS problem in the browser.

Good catch!

2023-08-29 12:06 UTC, SvenMarcus approved these changes

2023-08-29 13:19 UTC, merged